language: android
android:
  components:


    # The BuildTools version used by your project
    - build-tools-21.1.0

    # The SDK version used to compile your project
    - android-21

script: 
   - ./build.sh
