language: android
android:
  components:


    # The BuildTools version used by your project
    - build-tools-21.1.0

    # The SDK version used to compile your project
    - android-21
    - sys-img-armeabi-v7a-android-21

before_script: 
  - chmod +x ./gradlew

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "Dobby233Liu"
      - git config --local user.email "papaqi1234567@126.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: "54e78340b914cad8050d37819c8f567d3a2f6628"
  file_glob: true
  file: app/build/outputs/apk/debug/app-debug.apk
  skip_cleanup: true
  name: "$(date +'%Y%m%d%H%M%S') release"
  prerelease: true
